WIP: Convert Modal view to React components
menpo/landmarker.io pull request #140
Opened 2017-05-17 11:29 UTC by gabrielcowley

_This PR has a staging branch, which means a production build of this branch exists and can be launched. [**Click here**](https://www.landmarker.io/staging/react_modal) to preview this PR._

This PR converts the Modal view which is currently a Backbone View into React components and integrates it into the `reactbridge`.

This PR is to be merged after [PR #138](https://github.com/menpo/landmarker.io/pull/138).

2017-05-17 17:47 UTC, jabooth commented
@gabrielcowley can you pull and merge `ts_react` to clean up the diff here?

2017-05-17 17:48 UTC, gabrielcowley commented
@jabooth Will do

2017-05-17 21:52 UTC, jabooth requested changes
Few specific things, and seems the connection in `reactbridge` is missing. 

I think `src/ts/app/model/modals.ts` can be simplified a lot, but this will become clearer once we see the integration. 

Remember, React creates the illusion of re-rendering the entire tree on every state change. The top level Modal manager class can itself be a React component that has state which tracks what Modals are currently open. It should wire up the callbacks so that changes registered from modals (i.e. clicking the cancel button) will update the state of the main modal manger in addition to the action that we wish to have performed.

Maybe this would be clearer to discuss in person on Skype @gabrielcowley?

2017-05-17 21:52 UTC, jabooth commented on src/ts/app/view/components/PromptModal.tsx
> +export interface PromptModalProps {
here we can write 
```
export interface PromptModalProps extends ModalProps
```
so we don't have to redeclare common fields

2017-05-17 21:52 UTC, jabooth commented on src/ts/app/view/components/PromptModal.tsx
> +import { Modal } from './Modal'
```ts
import { Modal, PromptModalProps } from './Modal'
```

2017-05-17 21:52 UTC, jabooth commented on src/ts/app/view/components/ConfirmModal.tsx
> +function acceptOrReject(acceptReject: (() => void) | undefined, close: () => void): void {
maybe more natural to make `acceptReject` optional (which means we have to put it last)
```ts
function acceptOrReject(close: () => void, acceptReject?: () => void)): void 
```

2017-05-17 21:52 UTC, jabooth commented on src/ts/app/view/components/ConfirmModal.tsx
> +                    <div className="ConfirmAction--Yes" onClick={() => acceptOrReject(props.accept, props.close)}>Yes</div>
if we do as above, flip args here

2017-05-17 21:52 UTC, jabooth commented on src/ts/app/view/reactbridge.ts
>          const help = Help(props)
it seems there should be more extensive change to `reactbridge` to integrate the new React Modal (doesn't seem to currently be used?)

2017-05-31 11:05 UTC, gabrielcowley commented
All modals have been converted to React. The Intro modal still exists in Backbone form and the old version is still used for when Landmarker is opened. Replacing this with its React version would require a significant overhaul of the startup process. I'm happy for this to be merged as it is.

2017-06-01 23:22 UTC, jabooth commented
@gabrielcowley OK, in the interest of unblocking let's get this merged, I'll circle back and tidy up the intro stuff later.

2017-06-01 23:22 UTC, merged